### ISSUE TITLE
Merged children

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/metaproject#3]
Testing your fix for #2

What am I doing wrong?

The demo.sql test runs fine, but I can't get it to run on the QGEP database

```
{
  "od_damage": {
    "pkey_nextval": " qgep.generate_oid(''od_damage'')", 
    "inherited_by": {
      "od_damage_manhole": {
        "inherits": "od_damage", 
        "table_name": "qgep.od_damage_manhole", 
        "pkey": "obj_id"
      }, 
      "od_damage_channel": {
        "inherits": "od_damage", 
        "table_name": "qgep.od_damage_channel", 
        "pkey": "obj_id"
      }
    }, 
    "table_name": "qgep.od_damage", 
    "merge_view": {
      "destination_schema": "qgep", 
      "view_name": "vw_od_damage"
    }, 
    "pkey": "obj_id"
  }
}
```

```
Traceback (most recent call last):
  File "/home/mku/dev/qgep/metaproject/create_views.py", line 48, in <module>
    cur.execute("SELECT qgep.fn_inherited_table_view('{}'::json)".format(json.dumps(viewdef)))
psycopg2.ProgrammingError: column "connection" specified more than once
CONTEXT:  SQL statement "CREATE OR REPLACE VIEW qgep.vw_od_damage AS SELECT
			CASE 
				WHEN od_damage_manhole.obj_id IS NOT NULL THEN 'od_damage_manhole'::qgep.od_damage_type 
				WHEN od_damage_channel.obj_id IS NOT NULL THEN 'od_damage_channel'::qgep.od_damage_type 
			ELSE NULL::qgep.od_damage_type END AS od_damage_type,
			od_damage.obj_id ,
			 	od_damage.comments,
					 od_damage.single_damage_class,
					 od_damage.last_modification,
					 od_damage.dataowner,
					 od_damage.provider,
					 od_damage.fs_examination , od_damage_manhole.connection, od_damage_manhole.damage_code_manhole, od_damage_manhole.damage_reach, od_damage_manhole.dammage_begin, od_damage_manhole.dammage_end, od_damage_manhole.distance, od_damage_manhole.quantification1, od_damage_manhole.quantification2, od_damage_manhole.video_counter, od_damage_manhole.view_parameters, od_damage_manhole.yyy_manhole_schachtbereich, od_damage_channel.channel_damage_code, od_damage_channel.connection, od_damage_channel.damage_begin, od_damage_channel.damage_reach, od_damage_channel.dammage_end, od_damage_channel.distance, od_damage_channel.quantification1, od_damage_channel.quantification2, od_damage_channel.video_counter, od_damage_channel.view_parameters
			FROM qgep.od_damage od_damage
				LEFT JOIN qgep.od_damage_manhole od_damage_manhole ON od_damage.obj_id = od_damage_manhole.obj_id 
				LEFT JOIN qgep.od_damage_channel od_damage_channel ON od_damage.obj_id = od_damage_channel.obj_id  "
PL/pgSQL function qgep.fn_inherited_table_view(json) line 270 at EXECUTE statement
```

**Comment by 3nids** [comment]
There is no merge_columns in the merge_view

**Comment by m-kuhn** [comment]
It seems to get a bit further

```
{
  "od_damage": {
    "pkey": "obj_id", 
    "inherited_by": {
      "od_damage_manhole": {
        "inherits": "od_damage", 
        "table_name": "qgep.od_damage_manhole", 
        "pkey": "obj_id"
      }, 
      "od_damage_channel": {
        "inherits": "od_damage", 
        "table_name": "qgep.od_damage_channel", 
        "pkey": "obj_id"
      }
    }, 
    "table_name": "qgep.od_damage", 
    "merge_view": {
      "destination_schema": "qgep", 
      "view_name": "vw_od_damage", 
      "merge_columns": {
        "quantification2": {
          "od_damage_manhole": "quantification2", 
          "od_damage_channel": "quantification2"
        }, 
        "distance": {
          "od_damage_manhole": "distance", 
          "od_damage_channel": "distance"
        }, 
        "quantification1": {
          "od_damage_manhole": "quantification1", 
          "od_damage_channel": "quantification1"
        }, 
        "video_counter": {
          "od_damage_manhole": "video_counter", 
          "od_damage_channel": "video_counter"
        }, 
        "damage_reach": {
          "od_damage_manhole": "damage_reach", 
          "od_damage_channel": "damage_reach"
        }, 
        "view_parameters": {
          "od_damage_manhole": "view_parameters", 
          "od_damage_channel": "view_parameters"
        }, 
        "connection": {
          "od_damage_manhole": "connection", 
          "od_damage_channel": "connection"
        }, 
        "dammage_end": {
          "od_damage_manhole": "dammage_end", 
          "od_damage_channel": "dammage_end"
        }
      }
    }, 
    "pkey_nextval": " qgep.generate_oid(''od_damage'')"
  }
}
```
```
Traceback (most recent call last):
  File "/home/mku/dev/qgep/metaproject/create_views.py", line 86, in <module>
    raise e
psycopg2.ProgrammingError: CASE types character varying and integer cannot be matched
LINE 15: ...   WHEN od_damage_channel.obj_id IS NOT NULL THEN od_damage_...
                                                              ^
QUERY:  CREATE OR REPLACE VIEW qgep.vw_od_damage AS SELECT
			CASE 
				WHEN od_damage_manhole.obj_id IS NOT NULL THEN 'od_damage_manhole'::qgep.od_damage_type 
				WHEN od_damage_channel.obj_id IS NOT NULL THEN 'od_damage_channel'::qgep.od_damage_type 
			ELSE NULL::qgep.od_damage_type END AS od_damage_type,
			od_damage.obj_id ,
			 	od_damage.comments,
					 od_damage.single_damage_class,
					 od_damage.last_modification,
					 od_damage.dataowner,
					 od_damage.provider,
					 od_damage.fs_examination 
				, CASE
					WHEN od_damage_manhole.obj_id IS NOT NULL THEN od_damage_manhole.quantification2
					WHEN od_damage_channel.obj_id IS NOT NULL THEN od_damage_channel.quantification2
				END AS quantification2
				, CASE
					WHEN od_damage_manhole.obj_id IS NOT NULL THEN od_damage_manhole.distance
					WHEN od_damage_channel.obj_id IS NOT NULL THEN od_damage_channel.distance
				END AS distance
				, CASE
					WHEN od_damage_manhole.obj_id IS NOT NULL THEN od_damage_manhole.quantification1
					WHEN od_damage_channel.obj_id IS NOT NULL THEN od_damage_channel.quantification1
				END AS quantification1
				, CASE
					WHEN od_damage_manhole.obj_id IS NOT NULL THEN od_damage_manhole.video_counter
					WHEN od_damage_channel.obj_id IS NOT NULL THEN od_damage_channel.video_counter
				END AS video_counter
				, CASE
					WHEN od_damage_manhole.obj_id IS NOT NULL THEN od_damage_manhole.damage_reach
					WHEN od_damage_channel.obj_id IS NOT NULL THEN od_damage_channel.damage_reach
				END AS damage_reach
				, CASE
					WHEN od_damage_manhole.obj_id IS NOT NULL THEN od_damage_manhole.view_parameters
					WHEN od_damage_channel.obj_id IS NOT NULL THEN od_damage_channel.view_parameters
				END AS view_parameters
				, CASE
					WHEN od_damage_manhole.obj_id IS NOT NULL THEN od_damage_manhole.connection
					WHEN od_damage_channel.obj_id IS NOT NULL THEN od_damage_channel.connection
				END AS connection
				, CASE
					WHEN od_damage_manhole.obj_id IS NOT NULL THEN od_damage_manhole.dammage_end
					WHEN od_damage_channel.obj_id IS NOT NULL THEN od_damage_channel.dammage_end
				END AS dammage_end, od_damage_manhole.damage_code_manhole, od_damage_manhole.dammage_begin, od_damage_manhole.yyy_manhole_schachtbereich, od_damage_channel.channel_damage_code, od_damage_channel.damage_begin
			FROM qgep.od_damage od_damage
				LEFT JOIN qgep.od_damage_manhole od_damage_manhole ON od_damage.obj_id = od_damage_manhole.obj_id 
				LEFT JOIN qgep.od_damage_channel od_damage_channel ON od_damage.obj_id = od_damage_channel.obj_id  
CONTEXT:  PL/pgSQL function qgep.fn_inherited_table_view(json) line 270 at EXECUTE statement
```

**Comment by m-kuhn** [comment]
https://github.com/QGEP/QGEP/issues/153

**Comment by m-kuhn** [comment]
Probably explained by the different data types of quantification fields (int vs. varchar). Not sure what we should do now... Probably skip the table until it's fixed upstream.

**Comment by m-kuhn** [comment]
Evereything else works. Good stuff!
